version: '3.9'

services:
  app:
    image: node:latest
    command: sh -c 'yarn && yarn dev'
    container_name: app
    environment:
      GID: 1000
      UID: 1000
      PORT: ${PORT:-3003}
    working_dir: /usr/share/app
    ports:
      - 3003:3003
    volumes:
      - ./:/usr/share/app
