name: dev
run-name: ${{ github.actor }} build ${{ github.repository }}
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
    - dev


jobs:
  build:
    runs-on: [ self-hosted, linux, x64, vm-01 ]
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            source ~/.zshrc
            cd ${{ secrets.WORK_DIR }}
            echo  ${{ github.repositoryUrl }}
            echo 'Pull new code ...'
            if [ -d ${{ secrets.WORK_DIR }}/test-gitops ];
            then cd test-gitops && git pull;
            else git clone https://github.com/Links-Corp/test-gitops.git && cd test-gitops
            fi
            echo 'Checkout to branch ${{ github.ref_name }} ...'
            git checkout ${{ github.ref_name }}
            echo 'Start app instance ...'
            yarn watch
      # - name: Delete app instance
      #   run: yarn stop
      #   continue-on-error: true

      # - name: Start app instance
      #   run: yarn watch

      # - name: check /about
      #   id: package_version
      #   run: |
      #     sleep 90
      #     npm_package_version=$(curl localhost:3002/about | jq '.npm_package_version' -r)
      #     if [ $npm_package_version ];
      #       then echo $npm_package_version && exit 0; else exit 1
      #     fi