name: dev
run-name: ${{ github.actor }} build ${{ github.repository }}
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
    - dev


jobs:
  build:
    runs-on: [ self-hosted, linux, x64, vm-01 ]
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            ls -alh
            echo  ${{ github.repositoryUrl }}
            if [ -d ${{ secrets.WORK_DIR }}/tests ];
              then cd tests && git pull;
              else git clone ${{ github.repositoryUrl }} && cd tests
            fi
      # - name: Delete app instance
      #   run: yarn stop

      # - name: Start app instance
      #   run: yarn watch
      #   if: failure()

      # - name: check /about
      #   id: package_version
      #   run: |
      #     sleep 90
      #     npm_package_version=$(curl localhost:3002/about | jq '.npm_package_version' -r)
      #     if [ $npm_package_version ];
      #       then echo $npm_package_version && exit 0; else exit 1
      #     fi