name: learn-github-actions-deploy
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
    - dev
    - main

jobs:
  deploy:
    runs-on: [ self-hosted, linux, x64, vm-01 ]
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Reclaim cache directory
        run: sudo chown -R $USER:$USER node_modules/
      - name: Run app
        run: docker compose up -d