name: Setup app
run-name: ${{ github.actor }} is setting up app
on:
  push:
    branches:
    - dev

jobs:
  deploy:
    runs-on: [ self-hosted, linux, x64, vm-01 ]
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.2.x
          cache: npm

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn