name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
    - dev
    - main

jobs:
  deploy:
    runs-on: [ self-hosted, linux, x64, vm-01 ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Set up yarn globally
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Reclaim cache directory
        run: sudo chown -R $USER:$USER node_modules/
      - name: Run app
        run: docker compose up -d

  test:
    runs-on: [ self-hosted, linux, x64, vm-01 ]
    steps:
      - name: Check app is running
        run: docker logs app
      - name: check /about
        run: curl localhost:3003/about | jq '.npm_package_version' -r