name: learn-github-actions-test
run-name: ${{ github.actor }} is learning GitHub Actions test
on:
  push:
    branches:
    - dev
    - main

jobs:
  test:
    runs-on: [ self-hosted, linux, x64, vm-01 ]
    steps:
      - name: Reclaim cache directory
        run: sudo chown -R $USER:$USER node_modules/
      - name: check /about
        id: package_version
        run: |
          if [ $(curl localhost:3003/about | jq '.npm_package_version' -r) = 1.0.0 ];
            then exit 0; else exit 1
          fi